In [1]:
import pandas as pd

In [2]:
PATH = '../data/raw/clubs.csv'
df = pd.read_csv(PATH)
df.head()

,club_id,club_code,name,domestic_competition_id,total_market_value,squad_size,average_age,foreigners_number,foreigners_percentage,national_team_players,stadium_name,stadium_seats,net_transfer_record,coach_name,last_season,filename,url
0,10,arminia-bielefeld,Arminia Bielefeld,L1,NaN,27,25.3,15,55.6,4,SchücoArena,26515,+€5.90m,NaN,2021,../data/raw/transfermarkt-scraper/2021/clubs.j...,https://www.transfermarkt.co.uk/arminia-bielef...
1,10004,paris-fc,Paris Football Club,FR1,NaN,31,28.7,17,54.8,9,Stade Jean Bouin,19904,€-72.30m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/paris-fc/start...
2,10010,esporte-clube-bahia,Esporte Clube Bahia,BRA1,NaN,32,26.7,6,18.8,3,Arena Fonte Nova,47364,+€8.14m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/esporte-clube-...
3,1003,leicester-city,Leicester City,GB1,NaN,29,25.9,17,58.6,9,King Power Stadium,32259,+€57.30m,Steve Cooper,2024,../data/raw/transfermarkt-scraper/2024/clubs.j...,https://www.transfermarkt.co.uk/leicester-city...
4,1005,us-lecce,Unione Sportiva Lecce,IT1,NaN,27,25.3,23,85.2,13,Ettore Giardiniero,31559,+€8.62m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/us-lecce/start...

In [3]:
df = df[['club_id', 'name', 'domestic_competition_id']]
df = df.rename(columns={'domestic_competition_id': 'league_id', 'name':'club_name'})
df.head()

   club_id              club_name league_id
0       10      Arminia Bielefeld        L1
1    10004    Paris Football Club       FR1
2    10010    Esporte Clube Bahia      BRA1
3     1003         Leicester City       GB1
4     1005  Unione Sportiva Lecce       IT1

In [4]:
ligas_8 = ['ES1', 'GB1', 'IT1', 'L1', 'ARG1', 'AUS1', 'COL1', 'JAP1']
df = df[df['league_id'].isin(ligas_8)].reset_index(drop=True)
df.head()

   club_id                   club_name league_id
0       10           Arminia Bielefeld        L1
1     1003              Leicester City       GB1
2     1005       Unione Sportiva Lecce       IT1
3    10090  Asociación Deportivo Pasto      COL1
4    10093      Independiente Medellín      COL1

In [5]:
df.shape[0]

228

In [6]:
df.to_csv('../data/clean/clubs_clean.csv', index=False)