In [1]:
import pandas as pd

In [2]:
PATH = '../data/raw/competitions.csv'

In [3]:
df = pd.read_csv(PATH)
df.head()

,competition_id,competition_code,name,sub_type,type,country_id,country_name,domestic_league_code,confederation,total_clubs,url
0,A1,bundesliga,bundesliga,first_tier,domestic_league,127,Austria,A1,europa,12.0,https://www.transfermarkt.co.uk/bundesliga/sta...
1,AFAC,afc-asian-cup,afc-asian-cup,afc_asian_cup,national_team_competition,-1,NaN,NaN,asien,NaN,https://www.transfermarkt.co.uk/afc-asian-cup/...
2,AFCN,africa-cup-of-nations,africa-cup-of-nations,africa_cup_of_nations,national_team_competition,-1,NaN,NaN,afrika,NaN,https://www.transfermarkt.co.uk/africa-cup-of-...
3,ARG1,torneo-apertura,torneo-apertura,first_tier,domestic_league,9,Argentina,ARG1,amerika,30.0,https://www.transfermarkt.co.uk/torneo-apertur...
4,AUS1,a-league-men,a-league-men,first_tier,domestic_league,12,Australia,AUS1,asien,12.0,https://www.transfermarkt.co.uk/a-league-men/s...

In [4]:
df = df[['competition_id', 'name']]
df.head()

  competition_id                   name
0             A1             bundesliga
1           AFAC          afc-asian-cup
2           AFCN  africa-cup-of-nations
3           ARG1        torneo-apertura
4           AUS1           a-league-men

In [5]:
top_5_ligas = ['laliga', 'premier-league', 'serie-a', 'bundesliga']
df = df[df['name'].isin(top_5_ligas)].reset_index(drop=True)
df.head()

  competition_id            name
0             A1      bundesliga
1            ES1          laliga
2            GB1  premier-league
3            IT1         serie-a
4             L1      bundesliga

In [6]:
df.to_csv('../data/clean/competitions_clean.csv', index=False)